const USER_CONSTANT = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
  UNSUBSCRIBE_ALL: 'UNSUBSCRIBE_ALL',
  INITSOCKET: 'INITSOCKET',
  FETCH_GROUP_MESSAGES: 'FETCH_GROUP_MESSAGES',
  SET_CHAT_HISTORY: 'SET_CHAT_HISTORY',
  ADD_CHAT_HISTORY: 'ADD_CHAT_HISTORY',
  SEND_GROUP_MESSAGE: 'SEND_GROUP_MESSAGE',
  LEAVE_CHAT: 'LEAVE_CHAT',
};
const PROJECT_CONSTANT = {
  GET_PROJECTS: 'GET_PROJECTS',
  GET_MYPROJECTS: 'GET_MYPROJECTS',
  GET_MEMBERS: 'GET_MEMBERS',
  PROJECT_GET_FAIL: 'PROJECT_GET_FAIL',
  GETCURRENT: 'GETCURRENT',
  GET_WORKLIST: 'GET_WORKLIST',
  GET_CURRENT_MEMBER: 'GET_CURRENT_MEMBER',
  SET_MESSAGE: 'SET_MESSAGE',
  SUCCESS_INSERT_COMMENT: 'SUCCESS_INSERT_COMMENT',
  GET_CURRENT_COMMENT: 'GET_CURRENT_COMMENT',
  LEAVE_WORK: 'LEAVE_WORK',
  SET_TEMP: 'SET_TEMP',
  ADD_TEMP: 'ADD_TEMP',
  UPDATE_TEMP: 'UPDATE_TEMP',
  GET_COUNT: 'GET_COUNT',
  SET_UPDATE: 'SET_UPDATE',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
};
const Constant = {
  ...USER_CONSTANT,
  ...PROJECT_CONSTANT,
};

export default Constant;
