const USER_CONSTANT = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
};
const PROJECT_CONSTANT = {
  GET_PROJECTS: 'GET_PROJECTS',
  GET_MYPROJECTS: 'GET_MYPROJECTS',
};
const Constant = {
  ...USER_CONSTANT,
  ...PROJECT_CONSTANT,
};

export default Constant;
