const USER_CONSTANT = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
};
const PROJECT_CONSTANT = {
  GET_PROJECTS: 'GET_PROJECTS',
  GET_MYPROJECTS: 'GET_MYPROJECTS',
  GET_MEMBERS: 'GET_MEMBERS',
  PROJECT_GET_FAIL: 'PROJECT_GET_FAIL',
  GETCURRENT: 'GETCURRENT',
};
const Constant = {
  ...USER_CONSTANT,
  ...PROJECT_CONSTANT,
};

export default Constant;
